### PR TITLE
lovebobatea

### PR DESCRIPTION
**Pull request by NewZlayerz**
It's my first time using this. Sorry if I did anything wrong ;-;

### CODE REVIEW

**Comment by thetkpark** [comment]
There is nothing wrong. :) Good to have you with us this evening. Thank you. 
**Bobatea is the best!!**

**Comment by NewZlayerz** [comment]
I just felt like I'm the only one with the file outside NOTE folder LOL.

**Comment by thetkpark** [comment]
Ohhhhhhhh. That's right. My baddd. LOL
It won't show on the page because they are not in the notes folder.
It's fine tho.

**Comment by NewZlayerz** [comment]
Okay, thanks. Also, thank you for changing the location :)

**Comment by thetkpark** [comment]
No problem ~

**Pull request merged**
